import sys
import pandas as pd
import numpy as np

def er(a, b) :
    s = 0 
    for i in range(len(a)) :
        s += (a[i] - b[i])**2
    s /= len(a)
    return s

#what to do is first
#1. 10 fold cross validation on train.csv
#2. a) total error = summation error in one fold. b) error in one fold = mean of square of error
#3. 

mode = sys.argv[1]  # 'b'
train_file = sys.argv[2]  # 'data/train.csv'
test_file = sys.argv[3]  # 'data/test.csv'
regularization_file = sys.argv[4]  # 'data/regularization.txt'
model_predictions_file = sys.argv[5]  # 'data/modelpredictions.txt'
model_weights_file = sys.argv[6]  # 'data/modelweights.txt'
best_lambda_file = sys.argv[7]  # 'data/bestlambda.txt'

data = pd.read_csv(train_file)
data.insert(0, 'X', 1)
x = data.drop(columns='Total Costs').to_numpy(dtype=np.float64)     #total training set
y = data['Total Costs'].to_numpy(dtype=np.float64)                  #training output
lambd = np.genfromtxt(regularization_file, dtype=np.float64)    #value of hyperparameters
n_lambda = len(lambd)
error = np.zeros(n_lambda)      # array for storing errors for each fold for each value of lambda

# w = np.linalg.pinv(x)@y
print(x.shape)

folds = np.split(x[:-4], 10)
out_folds = np.split(y[:-4], 10) 

# for k in range(10) :
#     test = folds[k]
#     train = np.concatenate([folds[i] for i in range(10) if i != k], axis=0, dtype=np.float64)
#     train_out = np.concatenate([out_folds[i] for i in range(10) if i != k], axis=0, dtype=np.float64)
#     xtx = train.T@train     #reduce the repetitive task by storing the constant val
#     n = xtx.shape[0]
#     # store error generated by all lambda for the given fold
#     for i in range(n_lambda) :
#         w = np.linalg.inv(xtx + lambd[i]*np.identity(n, dtype=np.float64))@(train.T@train_out) 
#         error[i] += er(out_folds[k], test@w)

min_er = min(error)
best_lambda = 2
# for i in range(n_lambda) :
#     if(min_er == error[i]) :
#         best_lambda = lambd[i] 
#         break 
# np.savetxt(best_lambda_file, np.array([2])) # stores best lambda

# training with best lambda
n = x.shape[1]
w = np.linalg.inv(x.T@x + best_lambda*np.identity(n, dtype=np.float64))@(x.T@y)

np.savetxt(model_weights_file, w)   # stores model weights
# fetch test data
data_new = pd.read_csv(test_file)
data_new.insert(0, 'X', 1)
x_new = data_new.to_numpy(dtype=np.float64)
# np.savetxt(model_predictions_file, x_new@w)  # stores prediction
y_pred = x_new@w

y_act = pd.read_csv('data/test_pred.csv').to_numpy(dtype=np.float64)
# error = y_act - y_pred
mse = 0
for i in range(len(y_act)) :
    mse += (y_act[i] - y_pred[i])**2
mse /= len(y_act) 
print(mse)